# See https://github.com/lightbody/browsermob-proxy#rest-api
bmpAPI <- list(
  openPort = list(method = "POST", path = "proxy", group = "session"),
  getPorts = list(method = "GET", path = "proxy", group = "session"),
  closeProxy = list(method = "DELETE", path = "proxy/{{port}}", 
                    group = "session"),
  waitForTraffic = list(method = "PUT", path = "proxy/{{port}}/wait", 
                        group = "session"),
  timeouts = list(method = "PUT", path = "proxy/{{port}}/timeout", 
                  group = "session"),
  setRetry = list(method = "PUT", path = "proxy/{{port}}/retry", 
                  group = "session"),
  emptyDNS = list(method = "DELETE", path = "proxy/{{port}}/dns/cache",
                  group = "session"),
  createHAR = list(method = "PUT", path = "proxy/{{port}}/har", 
                   group = "har"),
  newPage = list(method = "PUT", path = "proxy/{{port}}/har/pageRef", 
                 group = "har"),
  getHAR = list(method = "GET", path = "proxy/{{port}}/har", 
                group = "har"),
  getWhiteList = list(method = "GET", path = "proxy/{{port}}/whitelist",
                      group = "bwlist"),
  setWhiteList = list(method = "PUT", path = "proxy/{{port}}/whitelist",
                      group = "bwlist"),
  getBlackList = list(method = "GET", path = "proxy/{{port}}/blacklist",
                      group = "bwlist"),
  addURLBlackList = list(method = "PUT", 
                         path = "proxy/{{port}}/blacklist",
                         group = "bwlist"),
  clearBlackList = list(method = "DELETE", 
                        path = "proxy/{{port}}/blacklist",
                        group = "bwlist"),
  limitBandwidth = list(method = "PUT", path = "proxy/{{port}}/limit",
                        group = "bandwidth"),
  getBWremaining = list(method = "GET", path = "proxy/{{port}}/limit",
                        group = "bandwidth"),
  setHeaders = list(method = "POST", path = "proxy/{{port}}/headers",
                    group = "overwrite"),
  remapHosts = list(method = "POST", path = "proxy/{{port}}/hosts",
                    group = "overwrite"),
  setAutoBAuth = list(method = "POST", 
                      path = "proxy/{{port}}/auth/basic/{{domain}}",
                      group = "overwrite"),
  rewriteURL = list(method = "PUT", path = "proxy/{{port}}/rewrite",
                    group = "overwrite"),
  removeRewrites = list(method = "DELETE", "proxy/{{port}}/rewrite",
                        group = "overwrite"),
  reqInterceptor = list(method = "POST", 
                        path = "proxy/{{port}}/filter/request",
                        group = "intercept"),
  resInterceptor = list(method = "POST", 
                        path = "proxy/{{port}}/filter/response",
                        group = "intercept")
)
