# See https://github.com/lightbody/browsermob-proxy#rest-api
bmpAPI <- list(
  getPorts = list(method = "GET", path = "/proxy"),
  createHAR = list(method = "PUT", path = "/proxy/{{port}}/har"),
  newPage = list(method = "PUT", path = "/proxy/{{port}}/har/{{pageRef}}"),
  closeProxy = list(method = "DELETE", path = "/proxy/{{port}}"),
  getHAR = list(method = "GET", path = "/proxy/{{port}}/har"),
  getWhiteList = list(method = "GET", path = "/proxy/{{port}}/whitelist"),
  setWhiteList = list(method = "PUT", path = "/proxy/{{port}}/whitelist"),
  getBlackList = list(method = "GET", path = "/proxy/{{port}}/blacklist"),
  addURLBlackList = list(method = "PUT", 
                         path = "/proxy/{{port}}/blacklist"),
  clearBlackList = list(method = "DELETE", 
                        path = "/proxy/{{port}}/blacklist"),
  limitBandwidth = list(method = "PUT", path = "/proxy/{{port}}/limit"),
  getBWremaining = list(method = "GET", path = "/proxy/{{port}}/limit"),
  setHeaders = list(method = "POST", path = "/proxy/{{port}}/headers"),
  remapHosts = list(method = "POST", path = "/proxy/{{port}}/hosts"),
  setAutoBAuth = list(method = "POST", 
                      path = "/proxy/{{port}}/auth/basic/{{domain}}"),
  waitForTraffic = list(method = "PUT", path = "/proxy/{{port}}/wait"),
  timeouts = list(method = "PUT", path = "proxy/{{port}}/timeout"),
  rewriteURL = list(method = "PUT", path = "/proxy/{{port}}/rewrite"),
  removeRewrites = list(method = "DELETE", "/proxy/{{port}}/rewrite"),
  setRetry = list(method = "PUT", path = "/proxy/{{port}}/retry"),
  emptyDNS = list(method = "DELETE", path = "/proxy/{{port}}/dns/cache"),
  reqInterceptor = list(method = "POST", 
                        path = "/proxy/{{port}}/filter/request"),
  resInterceptor = list(method = "POST", 
                        path = "/proxy/{{port}}/filter/response")
)
